# Generated by Django 3.2.13 on 2022-05-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=254, null=True)),
                ('destination', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=30)),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('transfer', 'transfer'), ('withdrawal', 'withdrawal')], max_length=254)),
                ('status', models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('pending', 'pending')], max_length=254)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('fee', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
