# Generated by Django 3.2.13 on 2022-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'uccess'), ('fail', 'fail'), ('pending', 'pending')], max_length=254),
        ),
    ]
