# Generated by Django 4.0.4 on 2022-04-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
