# Generated by Django 3.2.13 on 2022-07-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='web/banners')),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(upload_to='web/descriptions')),
                ('button_title', models.CharField(blank=True, max_length=256, null=True)),
                ('button_link', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(upload_to='web/Features')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(blank=True, max_length=256, null=True)),
                ('slogan_text', models.CharField(blank=True, max_length=256, null=True)),
                ('instagram_image', models.ImageField(blank=True, default='web/footer/socials/default.png', null=True, upload_to='web/footer/socials')),
                ('instagram_link', models.CharField(blank=True, max_length=256, null=True)),
                ('linkedin_image', models.ImageField(blank=True, default='web/footer/socials/default.png', null=True, upload_to='web/footer/socials')),
                ('linkedin_link', models.CharField(blank=True, max_length=256, null=True)),
                ('youtube_image', models.ImageField(blank=True, default='web/footer/socials/default.png', null=True, upload_to='web/footer/socials')),
                ('youtube_link', models.CharField(blank=True, max_length=256, null=True)),
                ('facebook_image', models.ImageField(blank=True, default='web/footer/socials/default.png', null=True, upload_to='web/footer/socials')),
                ('facebook_link', models.CharField(blank=True, max_length=256, null=True)),
                ('medium_image', models.ImageField(blank=True, default='web/footer/socials/default.png', null=True, upload_to='web/footer/socials')),
                ('medium_link', models.CharField(blank=True, max_length=256, null=True)),
                ('whatsapp_image', models.ImageField(blank=True, default='web/footer/socials/default.png', null=True, upload_to='web/footer/socials')),
                ('whatsapp_link', models.CharField(blank=True, max_length=256, null=True)),
                ('discord_image', models.ImageField(blank=True, default='web/footer/socials/default.png', null=True, upload_to='web/footer/socials')),
                ('discord_link', models.CharField(blank=True, max_length=256, null=True)),
                ('reddit_image', models.ImageField(blank=True, default='web/footer/socials/default.png', null=True, upload_to='web/footer/socials')),
                ('reddit_link', models.CharField(blank=True, max_length=256, null=True)),
                ('telegram_image', models.ImageField(blank=True, default='web/footer/socials/default.png', null=True, upload_to='web/footer/socials')),
                ('telegram_link', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='web/mobilebanners')),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan_text', models.CharField(blank=True, max_length=256, null=True)),
                ('buttonText_text', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
