# Generated by Django 3.2.13 on 2022-08-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220801_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='discord_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='discord_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='facebook_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='linkedin_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='medium_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='medium_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='reddit_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='reddit_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='telegram_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='whatsapp_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube_link',
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(default='web/footer/socials/default.png', upload_to='web/footer/socials')),
                ('link', models.CharField(max_length=256)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.footer')),
            ],
        ),
    ]
