# Generated by Django 3.2.13 on 2022-08-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220801_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
