# Generated by Django 3.2.13 on 2022-06-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_conf_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conf_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
