# Generated by Django 3.2.13 on 2022-07-12 12:23

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_invitation_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitation_referral',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', editable=False, length=8, max_length=15, prefix=''),
        ),
    ]
