# Generated by Django 3.2.13 on 2022-07-12 12:24

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_invitation_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitation_referral',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', blank=True, editable=False, length=8, max_length=15, null=True, prefix=''),
        ),
    ]
