# Generated by Django 3.2.13 on 2022-07-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_invitation_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invitation_referral',
        ),
    ]
