# Generated by Django 3.2.13 on 2022-07-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_invitation_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_users',
            field=models.IntegerField(default=0),
        ),
    ]
