# Generated by Django 3.2.13 on 2022-06-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_auto_20220623_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeerates',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
