# Generated by Django 4.0.4 on 2022-04-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='inventory',
            field=models.DecimalField(decimal_places=5, max_digits=30),
        ),
    ]
