# Generated by Django 4.0.4 on 2022-04-21 08:52

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', unique=True),
        ),
    ]
