# Generated by Django 3.2.13 on 2022-07-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_banner_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winners_qty', models.IntegerField(default=0)),
                ('bonus_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
