# Generated by Django 3.2.13 on 2022-07-25 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0003_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winner',
            options={'verbose_name': 'Winners setting', 'verbose_name_plural': 'Winners settings'},
        ),
        migrations.CreateModel(
            name='WinnersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
