# Generated by Django 3.2.13 on 2022-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_auto_20220725_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
