# Generated by Django 3.2.13 on 2022-05-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inventory',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
    ]
