# Generated by Django 3.2.13 on 2022-09-19 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('destination', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=30)),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('transfer', 'transfer'), ('withdrawal', 'withdrawal')], max_length=256)),
                ('status', models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('pending', 'pending')], max_length=256)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('fee', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('daily', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='DepoHash',
            fields=[
                ('amount', models.DecimalField(decimal_places=5, max_digits=30)),
                ('token', models.CharField(choices=[('BUSD', 'BUSD'), ('BTC', 'BTC'), ('ETH', 'ETH'), ('USDT', 'USDT')], max_length=60)),
                ('network', models.CharField(choices=[('ERC20', 'ERC20'), ('BEP20', 'BEP20')], max_length=60)),
                ('deposit_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=16, max_length=40, prefix='', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
