# Generated by Django 3.2.13 on 2022-06-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('daily', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
            ],
        ),
    ]
